version: '3.1'

services:

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    volumes: 
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 9000:80
    volumes: 
      - pgadmin:/var/lib/pgadmin
    depends_on: 
      - database

  app:
    build:
      context: .
      args: 
        - NO_RUN_MIGRATION= 1
    volumes: 
      - ./src:/usr/src/app/src
    environment: 
      - NODE_ENV=development
      - POSTGRES_URL=postgres://postgres:123@database:5432/dbname
    ports: 
      - 4000:4000
    command: yarn dev & yarn migrate
    depends_on:
      - database

volumes:
  pgdata:
  pgadmin: